# Generated by Django 5.1.4 on 2026-09-27 03:54

from django.db import migrations, models


def tool_used_to_tool_calls(apps, schema_editor):
    """Carry each old single tool name over as a one-item tool_calls list.

    The old column never stored the tool's arguments, so those come across
    as {} - there's nothing to recover them from.
    """
    Message = apps.get_model("chat", "Message")
    for message in Message.objects.exclude(tool_used=""):
        message.tool_calls = [{"name": message.tool_used, "args": {}}]
        message.save(update_fields=["tool_calls"])


def tool_calls_to_tool_used(apps, schema_editor):
    Message = apps.get_model("chat", "Message")
    for message in Message.objects.exclude(tool_calls=[]):
        message.tool_used = message.tool_calls[0]["name"]
        message.save(update_fields=["tool_used"])


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='turn_messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(tool_used_to_tool_calls, tool_calls_to_tool_used),
        migrations.RemoveField(
            model_name='message',
            name='tool_used',
        ),
    ]
