# Generated by Django 5.1.4 on 2026-09-07 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('latency_ms', models.PositiveIntegerField()),
                ('model_call_count', models.PositiveIntegerField(default=0, help_text='Number of LLM calls this turn made (workflow steps).')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text="[{'name': ..., 'args': {...}}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='chat.conversation')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
