# Generated by Django 5.1.4 on 2026-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_tool_calls_and_turn_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
